spring:
  application:
    name: 'GameServer'
  datasource:
    url: jdbc:postgresql://localhost:5432/space-battle
    driverClassName: org.postgresql.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: SpaceBattle
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.kafka.listener.ack-mode: MANUAL
        spring.kafka.consumer.enable-auto-commit: false
        allow.auto.create.topics: true
      topic: 'space-battle-request-topic'

    producer:
      bootstrap-servers: localhost:9092
      group-id: SpaceBattle
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        allow.auto.create.topics: true
      topic: 'space-battle-response-topic'
server:
  port: 8081
  gameProcessServer:
    url: localhost:8082

token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
